version: "3"
services:
  frontend:
    build:
        context: ./frontend
        dockerfile: ../docker/frontend/Dockerfile
    container_name: m152-frontend
    ports:
        - 5000:80
    restart: unless-stopped
    depends_on:
        - web
    environment:
        - VITE_BACKEND_URL=http://localhost:8020
    healthcheck:
        test: curl --fail -s http://localhost:80 || exit 1
        interval: 60s
        retries: 5
        start_period: 20s
        timeout: 5s

  #  app:
  #    depends_on:
  #      - mysqldb
  #    build: ./bezkoder-app
  #    restart: on-failure
  #    env_file: ./.env
  #    ports:
  #      - ${SPRING_LOCAL_PORT}:${SPRING_DOCKER_PORT}
  #    environment:
  #      SPRING_APPLICATION_JSON: '{
  #          "spring.datasource.url"  : "jdbc:mysql://mysqldb:${MYSQLDB_DOCKER_PORT}/${MYSQLDB_DATABASE}?useSSL=false",
  #          "spring.datasource.username" : "${MYSQLDB_USER}",
  #          "spring.datasource.password" : "${MYSQLDB_ROOT_PASSWORD}",
  #          "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
  #          "spring.jpa.hibernate.ddl" : "true,"
  #          "spring.jpa.hibernate.ddl-auto" : "create"}'
  #    volumes:
  #      - .m2:/root/.m2
  #    stdin_open: true
  #    tty: true

  mysqldb:
    image: mysql:8.0
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQLDB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQLDB_DATABASE}
    ports:
      - ${MYSQLDB_LOCAL_PORT}:${MYSQLDB_DOCKER_PORT}
    volumes:
      - db:/var/lib/mysql
      - ./db-data/:/var/lib/mysql/
      - ./db-init/:/docker-entrypoint-initdb.d/


volumes:
  db:
